In [1]:
import pandas as pd

In [38]:
df = pd.read_csv("labels/labels_georgian_honey_2023-02-17-05-08-17.csv")
df

,label_name,bbox_x,bbox_y,bbox_width,bbox_height,image_name,image_width,image_height
0,0ა,392,753,91,158,IMG_20230212_162744.jpg,1200,1600
1,26ც,492,756,85,155,IMG_20230212_162744.jpg,1200,1600
2,30ხ,580,750,100,161,IMG_20230212_162744.jpg,1200,1600
3,5ვ,677,756,88,155,IMG_20230212_162744.jpg,1200,1600
4,8ი,762,756,94,155,IMG_20230212_162744.jpg,1200,1600
...,...,...,...,...,...,...,...,...
1297,21ქ,2152,3226,236,630,IMG_20230215_140933 (1).jpg,3456,4608
1298,18ტ,2353,3331,262,507,IMG_20230215_140933 (1).jpg,3456,4608
1299,20ფ,1575,2789,297,498,IMG_20230215_140933 (1).jpg,3456,4608
1300,18ტ,207,1503,279,503,IMG_20230215_150353.jpg,2456,3272
1301,19უ,474,1577,286,404,IMG_20230215_150353.jpg,2456,3272

In [39]:
df["label_id"] = df["label_name"].apply(lambda x: int(x[:-1]))
df["geo_letter"] = df["label_name"].apply(lambda x: x[-1])

In [40]:
df.groupby(["label_id"])["geo_letter"].value_counts().sort_values(ascending=False)

label_id  geo_letter
8         ი             105
0         ა              99
16        რ              87
4         ე              79
17        ს              74
10        ლ              67
12        ნ              63
13        ო              62
1         ბ              58
19        უ              56
3         დ              53
5         ვ              50
11        მ              50
18        ტ              46
7         თ              41
9         კ              37
20        ფ              35
2         გ              34
21        ქ              32
30        ხ              26
24        შ              22
6         ზ              20
14        პ              18
26        ც              17
28        წ              17
25        ჩ              12
23        ყ              11
27        ძ              10
22        ღ               9
15        ჟ               5
31        ჯ               4
29        ჭ               2
32        ჰ               1
Name: geo_letter, dtype: int64